global:
  message: "Welcome to customer service dev environment!!"

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_dev
    username: root
    password: Deens@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
