spring:
  applciation:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/customerdb_master
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
