spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: root
    password: Deens@1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

global:
  message: "Welcome to customer PROD environment!"
