spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: Deens@1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

global:
  message: "Welcome to order DEV environment!"
